import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen flex-col`}
            >
                <Navbar />
                <main className="mx-auto w-full max-w-7xl flex-1 px-4 py-8">
                    {children}
                </main>
                <footer className="py-6 text-center text-sm text-gray-400">
                    © 2025 Riftbound TCG. All rights reserved.
                </footer>
            </body>
        </html>
    );
}
